info:
  app:
    name: My Spring Boot Application
    description: A simple Spring Boot application
    version: 1.0.0
  contact:
    name: Yuri Claro
    email: yuriclaro@outlook.com
spring:
  application:
    name: yuriclaro-exercicio-spring-boot-1
  datasource:
    url: jdbc:postgresql://localhost:5432/springboot1
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
  springdoc:
    swagger-ui:
      path: /swagger-ui.html
  management:
    endpoints:
      web:
        exposure:
          include: health, info
  spring:
    boot:
      admin:
        client:
          url: http://localhost:8082